---

version: '2'

services:
  mysql:
    image: mysql:8.2.0
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - ./files/mysql:/docker-entrypoint-initdb.d
volumes:
  mysql-data: